import { Painting, NavItem } from './types';

export const NAV_ITEMS: NavItem[] = [
  { name: 'Home', href: '#home' },
  { name: 'Gallery', href: '#gallery' },
  { name: 'About', href: '#about' },
  { name: 'Contact', href: '#contact' },
];

export const SOCIAL_MEDIA = {
  instagram: 'https://instagram.com/kiwiart',
  tiktok: 'https://tiktok.com/@kiwiart',
  facebook: 'https://facebook.com/kiwiart',
  viber: 'viber://chat?number=+84123456789', // Replace with your Viber number
  youtube: 'https://youtube.com/@kiwiart',
};

export const MOCK_PAINTINGS: Painting[] = [
  {
    id: '1',
    name: 'Ocean Depths',
    artist: 'Anya Sharma',
    description: 'A vibrant abstract representation of the deep ocean, crafted with Lapis Lazuli, Sodalite, and hints of Mother of Pearl to capture the play of light underwater. This piece evokes calm and mystery, perfect for a contemplative space.',
    price: 1250.00,
    originalPrice: 1500.00, // Added original price
    imageUrl: '/public/images/backround2.png',
    thumbnailUrl: '/public/images/backround2.png',
    materials: ['Lapis Lazuli', 'Sodalite', 'Mother of Pearl', 'Epoxy Resin'],
    dimensions: '24x36 inches',
    videoUrl: '/public/video/video demo.mp4',
    additionalImages: [
      '/public/images/backround2.png',
      '/public/images/backround3.png',
      '/public/images/backround4.png',
    ],
  },
  {
    id: '2',
    name: 'Forest Whispers',
    artist: 'David Lee',
    description: 'An enchanting depiction of an ancient forest, using rich Malachite, Peridot, and earthy Jasper. The textures bring the dense foliage and mossy ground to life, offering a serene escape into nature\'s embrace.',
    price: 980.00,
    imageUrl: '/public/images/backround5.png',
    thumbnailUrl: '/public/images/backround5.png',
    materials: ['Malachite', 'Peridot', 'Jasper', 'Wood Panel'],
    dimensions: '18x24 inches',
    additionalImages: [
      'https://picsum.photos/id/1083/800/600',
      'https://picsum.photos/id/1083/800/500',
    ],
  },
  {
    id: '3',
    name: 'Sunset Horizon',
    artist: 'Maria Garcia',
    description: 'Capturing the dramatic colors of a sunset over a distant horizon, with fiery Carnelian, warm Citrine, and deep Garnet. The gradation of colors provides a dynamic and uplifting presence, symbolizing hope and new beginnings.',
    price: 1500.00,
    originalPrice: 1750.00,
    imageUrl: '/public/images/backround5.png',
    thumbnailUrl: '/public/images/backround5.png',
    materials: ['Carnelian', 'Citrine', 'Garnet', 'Amethyst', 'Acrylic Board'],
    dimensions: '30x40 inches',
    videoUrl: '/public/video/video demo.mp4', // Another sample video
  },
  {
    id: '4',
    name: 'Celestial Bloom',
    artist: 'Kenji Tanaka',
    description: 'A fantastical celestial flower blooming in a cosmic garden, made with iridescent Labradorite, shimmering Moonstone, and deep blue Tanzanite. This piece reflects cosmic wonder and spiritual awakening.',
    price: 1800.00,
    imageUrl: '/public/images/backround5.png',
    thumbnailUrl: '/public/images/backround5.png',
    materials: ['Labradorite', 'Moonstone', 'Tanzanite', 'Black Onyx', 'Canvas'],
    dimensions: '28x28 inches',
    additionalImages: [
      'https://picsum.photos/id/1060/800/600',
      'https://picsum.photos/id/1060/800/500',
      'https://picsum.photos/id/1060/700/600',
    ],
  },
  {
    id: '5',
    name: 'Desert Bloom',
    artist: 'Lena Petrova',
    description: 'A vivid portrayal of desert flowers in full bloom after rain, using vibrant Turquoise, Coral, and earthy Sardonyx. It’s a testament to resilience and beauty in harsh environments, bringing warmth and color.',
    price: 1100.00,
    imageUrl: '/public/images/backround5.png',
    thumbnailUrl: '/public/images/backround5.png',
    materials: ['Turquoise', 'Coral', 'Sardonyx', 'Sandstone', 'Metal Frame'],
    dimensions: '20x30 inches',
  },
  {
    id: '6',
    name: 'Arctic Aurora',
    artist: 'Sasha Ivanova',
    description: 'Capturing the ethereal dance of the aurora borealis over icy landscapes, with shimmering Selenite, translucent Quartz, and hints of iridescent Opal. A mesmerizing piece that brings a touch of magic.',
    price: 1650.00,
    originalPrice: 1900.00,
    imageUrl: '/public/images/backround5.png',
    thumbnailUrl: '/public/images/backround5.png',
    materials: ['Selenite', 'Quartz', 'Opal', 'Blue Lace Agate', 'Glass'],
    dimensions: '24x48 inches',
    videoUrl: '/public/video/video demo.mp4',
  },
  {
    id: '7',
    name: 'Volcanic Heart',
    artist: 'Ramon Sanchez',
    description: 'An intense and powerful representation of a volcanic eruption, utilizing obsidian, fiery lava rock, and streaks of red jasper. This artwork embodies raw power and the earth\'s transformative energy.',
    price: 1300.00,
    imageUrl: '/public/images/backround5.png',
    thumbnailUrl: '/public/images/backround5.png',
    materials: ['Obsidian', 'Lava Rock', 'Red Jasper', 'Smoky Quartz', 'Concrete'],
    dimensions: '36x24 inches',
  },
  {
    id: '8',
    name: 'Zen Garden',
    artist: 'Hiroshi Sato',
    description: 'A serene and minimalist depiction of a zen garden, crafted with smooth river stones, subtle green aventurine, and white quartz. It promotes peace, balance, and meditative calm.',
    price: 850.00,
    originalPrice: 1000.00,
    imageUrl: '/public/images/backround5.png',
    thumbnailUrl: '/public/images/backround5.png',
    materials: ['River Stones', 'Green Aventurine', 'White Quartz', 'Sand', 'Bamboo Frame'],
    dimensions: '16x20 inches',
    additionalImages: [
      'https://picsum.photos/id/1000/800/600',
      'https://picsum.photos/id/1000/800/500',
    ],
  },
  {
    id: '9',
    name: 'Crystal Caverns',
    artist: 'Elara Vance',
    description: 'A dazzling journey into a hidden crystal cavern, featuring sparkling Amethyst, clear Quartz clusters, and vibrant Fluorite. The depth and luminescence create a sense of wonder and hidden treasures.',
    price: 1950.00,
    imageUrl: '/public/images/backround5.png',
    thumbnailUrl: '/public/images/backround5.png',
    materials: ['Amethyst', 'Quartz', 'Fluorite', 'Geode Slices', 'Light-Emitting Resin'],
    dimensions: '40x30 inches',
    videoUrl: '/public/video/video demo.mp4'
  },
];